FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER user
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB shops

# Copy initialization scripts to docker-entrypoint-initdb.d
COPY init.sql /docker-entrypoint-initdb.d/
