# Build stage
FROM golang:1.18 AS builder
WORKDIR /app
RUN go get github.com/ADSP-Project/Federation-Hub
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o authServer .

# Final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/authServer .
ENTRYPOINT ["./authServer"]

