# Stage 1: Build the Go application
FROM golang:1.18 AS builder
WORKDIR /app
RUN go get github.com/ADSP-Project/Federation-Hub
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main

# Stage 2: Create the final image with the compiled binary
FROM golang:1.18
WORKDIR /app
COPY --from=builder /app/main .
ENTRYPOINT ["./main"]


