apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: auth
    context: federation-hub
    docker:
      dockerfile:
        Dockerfile-auth
  - image: hub-db
    context: federation-hub
    docker:
      dockerfile:
        Dockerfile-DB
  - image: main
    context: federation-hub
    docker:
      dockerfile:
        Dockerfile-main
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
    - kubernetes-manifests
deploy:
  kubectl: {}