---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  labels:
    name: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: main
        env:
        - name: DB_HOST
          value: hub-db
        - name: DB_USER
          value: user
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: shops
        - name: HUB_PORT
          value: 8092
        - name: AUTH_SERVER
          value: auth
---
apiVersion: v1
kind: Service
metadata:
  name: main
  labels:
    name: main
spec:
  type: ClusterIP
  ports:
  - port: 8092
    targetPort: 8092
  selector:
    app: main